app/user/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, SelectField
from wtforms.validators import DataRequired, Length, Regexp, EqualTo, Email
from wtforms import ValidationError
from ..models import User
from flask_pagedown.fields import PageDownField


class LoginForm(FlaskForm):
    account = StringField('学号/帐号', validators=[DataRequired(), Length(1, 20)])
    password = PasswordField("密码", validators=[DataRequired()])
    remember_me = BooleanField('保持登录状态')
    submit = SubmitField('Log in')


class RegistrationForm(FlaskForm):
    # email = StringField('邮箱', validators=[DataRequired(), Length(1, 64), Email()])
    account = StringField('学号', validators=[DataRequired(), Length(2, 30)])
    username = StringField('真名', validators=[
        DataRequired(), Length(1, 64)])
    password = PasswordField('Password', validators=[
        DataRequired(), EqualTo('password2', message='Passwords must match.')])
    password2 = PasswordField('Confirm password', validators=[DataRequired()])
    submit = SubmitField('注册')

    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('邮箱已经注册.')

    def validate_account(self, field):
        if User.query.filter_by(account=field.data).first():
            raise ValidationError('学号/账户已被使用.')


class PostForm(FlaskForm):
    title = StringField('标题', validators=[DataRequired()])
    body = PageDownField('正文', validators=[DataRequired()])
    group = SelectField('组名', choices=[('Python', 'Python组'), ('Linux', 'Linux组')],
                        validators=[DataRequired()])
    submit = SubmitField('提交')


class HomeworkForm(FlaskForm):
    body = PageDownField('作业', validators=[DataRequired()])
    submit = SubmitField('提交')


class ChangePasswordForm(FlaskForm):
    old_password = PasswordField('旧密码', validators=[DataRequired()])
    password = PasswordField('新密码', validators=[
        DataRequired(), EqualTo('password2', message='两次密码必须相同')])
    password2 = PasswordField('重复密码', validators=[DataRequired()])
    submit = SubmitField('更新密码')

app/user/__init__.py
from flask import Blueprint

user = Blueprint('user', __name__)

from . import views

app/user/views.py
from flask import render_template, redirect, request, url_for, flash, abort
from flask_login import login_user, logout_user, login_required, current_user
from . import user
from .. import db
from ..models import User, Post, Homework
from .forms import LoginForm, RegistrationForm, PostForm, HomeworkForm, ChangePasswordForm


@user.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user_item = User.query.filter_by(account=form.account.data).first()
        print(user_item.username)
        print(user_item.account)
        if user_item is not None and user_item.verify_password(form.password.data):
            login_user(user_item, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('main.index'))
        # flash('Invalid username or password.')
        flash('无效的用户名或密码')
    return render_template('user/login.html', form=form)


@user.route('/logout')
@login_required
def logout():
    logout_user()
    flash("你已经登出了")
    return redirect(url_for('main.index'))


@user.route('/publish_homework', methods=['GET', 'POST'])
@login_required
def publish_homework():
    if current_user.is_teacher:
        form = PostForm()
        if form.validate_on_submit():
            post = Post(title=form.title.data,
                        body=form.body.data,
                        group=form.group.data,
                        author=current_user._get_current_object())
            db.session.add(post)
            return redirect(url_for('main.index'))
        return render_template('user/publish_homework.html', form=form)
    else:
        flash('Sorry, 你暂时没有该权限')
        return redirect(url_for('main.index'))


@user.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author:  # 防止别人修改....
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        db.session.add(post)
        flash('作业内容已被更新.')
        return redirect(url_for('user.post', id=post.id))
    form.title.data = post.title
    form.body.data = post.body
    return render_template('user/edit_post.html', form=form)


@user.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    if form.validate_on_submit():
        user_info = User(username=form.username.data,
                         account=form.account.data,
                         password=form.password.data)
        db.session.add(user_info)
        flash('现在可以进行登录了.')
        return redirect(url_for('user.login'))
    return render_template('user/register.html', form=form)


@user.route('/post/<int:id>', methods=['GET', 'POST'])
@login_required
def post(id):
    post = Post.query.get_or_404(id)
    form = HomeworkForm()
    if form.validate_on_submit():
        homework = Homework(body=form.body.data,
                            post=post,
                            author=current_user._get_current_object())
        db.session.add(homework)
        flash('你的作业已经提交')
        return redirect(url_for('user.post', id=post.id))
    return render_template('user/post.html', posts=[post], form=form)


@user.route('/stu_homework_list/<int:id>')
@login_required
def stu_homework_list(id):
    post = Post.query.get_or_404(id)
    if current_user != post.author:  # 防止别人修改....
        abort(403)
    homeworks = Homework.query.filter_by(post_id=id).all()
    return render_template('user/stu_homework_list.html', homeworks=homeworks)


@user.route('/stu_homework/<int:id>')
@login_required
def stu_homework(id):
    stu_homework = Homework.query.get_or_404(id)
    if current_user != stu_homework.author and current_user != stu_homework.post.author:
        abort(403)
    return render_template('user/stu_homework.html', stu_homework=stu_homework, post=stu_homework.post)


@user.route('/my_homework')
@login_required
def my_homework():
    homeworks = Homework.query.filter_by(author=current_user).all()
    return render_template('user/my_homework.html', homeworks=homeworks)


@user.route('/homework/edit/<int:id>', methods=['GET', 'POST'])
@login_required
def edit_homework(id):
    homework = Homework.query.get_or_404(id)
    if current_user != homework.author:
        abort(403)
    form = HomeworkForm()
    if form.validate_on_submit():
        homework.body = form.body.data
        db.session.add(homework)
        flash('作业回答已经更新.')
        return redirect(url_for('user.my_homework'))
    form.body.data = homework.body
    return render_template('user/edit_homework.html', form=form, homework=homework)


# @user.route('/user_info/<account>')  # 不存在的
# def user_info(account):
#     user = User.query.filter_by(account=account).first()
#     if user is None:
#         abort(404)
#     return render_template('user/user_info.html', user=user)


@user.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    form = ChangePasswordForm()
    if form.validate_on_submit():
        if current_user.verify_password(form.old_password.data):
            current_user.password = form.password.data
            db.session.add(current_user)
            flash('你的密码已经更新完成.')
            return redirect(url_for('main.index'))
        else:
            flash('无效的密码.')
    return render_template("user/change_password.html", form=form)

app/templates/user/change_password.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>修改密码</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/user/edit_homework.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block page_content %}
<div class="page-header">
    <h1>作业详细</h1>
</div>
<div class="post-content">
    <div class="post-title">{{ homework.post.title }}</div>
    <div class="post-body">
        {% if homework.post.body_html %}
            {{ homework.post.body_html | safe }}
        {% else %}
            {{ homework.post.body }}
        {% endif %}
    </div>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/user/edit_post.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<div class="page-header">
    <h1>编辑作业</h1>
</div>
<div>
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/user/login.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}

{% block title %}User login{% endblock %}

{% block page_content %}
<div class="page-header">
    <h1>Login</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
    <br>
    <p>新用户? <a href="{{ url_for('user.register') }}">点击注册</a></p>
</div>
{% endblock %}

app/templates/user/my_homework.html
{% extends "base.html" %}


{% block page_content %}
<div class="page-header">
    <h1>作业提交记录</h1>
</div>
<ul class="posts">
    {% for homework in homeworks %}
    <li class="homework">
        <div class="post-title">
            <a href="{{ url_for('user.edit_homework', id=homework.id) }}">{{ homework.post.title }}</a>
        </div>
        <div class="homework-content">
            <div class="homework-body">
                {% if homework.body_html %}
                    {{ homework.body_html | safe }}
                {% else %}
                    {{ homework.body }}
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
{% endblock %}

app/templates/user/post.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<ul class="posts">
    {% for post in posts %}
    <li class="post">
        <div class="post-content">
            <div class="post-title">{{ post.title }}</div>
            <div class="post-body">
                {% if post.body_html %}
                    {{ post.body_html | safe }}
                {% else %}
                    {{ post.body }}
                {% endif %}
            </div>
        </div>
    </li>
    {% endfor %}
</ul>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/user/publish_homework.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<div class="page-header">
    <h1>发布作业</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

{% block scripts %}
{{ super() }}
{{ pagedown.include_pagedown() }}
{% endblock %}

app/templates/user/register.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block page_content %}
<div class="page-header">
    <h1>注册</h1>
</div>
<div class="col-md-4">
    {{ wtf.quick_form(form) }}
</div>
{% endblock %}

app/templates/user/stu_homework.html
{% extends "base.html" %}

{% import "bootstrap/wtf.html" as wtf %}
{% block page_content %}
<div class="page-header">
    <h1>作业详细</h1>
</div>
<div class="post-content">
    <div class="post-title"><h2>标题:{{ post.title }}</h2></div>
    <div class="post-body">
        {% if post.body_html %}
            {{ post.body_html | safe }}
        {% else %}
            {{ post.body }}
        {% endif %}
    </div>
<div class="stu_homework-content">
    <div class="stu_homework-body">
        {% if stu_homework.body_html %}
            {{ stu_homework.body_html | safe }}
        {% else %}
            {{ stu_homework.body }}
        {% endif %}
    </div>
</div>

{% endblock %}

app/templates/user/stu_homework_list.html
{% extends "base.html" %}

{% block page_content %}
<div class="page-header">
    <h1>提交情况</h1>
</div>
<div class="table-responsive">
    <table class="table table-bordered">
        <tbody>
        {% for homework in homeworks %}
        <tr>
            <td>{{ homework.author.username }}</td>
            <td>
                <a href="{{ url_for('user.stu_homework', id=homework.id) }}">作业详细</a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}